image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      export PATH="$PATH:/home/gitpod/flutter/bin"
      flutter config --enable-web
      flutter doctor
    command: cd nannyphone_app && flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0

ports:
  - port: 8080
    onOpen: open-preview
